###  http://afshin:4044/ddd/api-ui
POST http://afshin:4044/ddd/finance/payed
Accept: application/json
Content-Type: application/json

{
  "customer":3,
  "transaction":"sb125954c",
  "transport": "2021-11-11 14:30:50"
}
################Carry##################################################################################
PUT http://afshin:4044/ddd/finance/carry
Accept: application/json
Content-Type: application/json

{
"code":10447
}