###  http://localhost:8083/ddd/api-ui
##### Show Cart #################################
POST http://afshin:4043/ddd/shopping/showcart
Accept: application/json
Content-Type: application/json

{
  "code":2
}
##### Add To Cart #################################
PUT http://afshin:4043/ddd/shopping/addtocart
Accept: application/json
Content-Type: application/json

{
  "customerfk": 2,
  "productfk": 28,
  "quantity": 0,
  "price": 20.20
}
##### Finalization Cart #################################
POST http://afshin:4043/ddd/shopping/closecart
Accept: application/json
Content-Type: application/json

{
  "code":2
}
##### Delete From Cart #################################
DELETE http://afshin:4043/ddd/shopping/deletefromcart
Accept: application/json
Content-Type: application/json

{
  "customercode":2,
  "productcode":29
}
##### cancel  Cart #################################
DELETE http://afshin:4043/ddd/shopping/cancelcart
Accept: application/json
Content-Type: application/json

{
  "code":3
}
##### Show Product #################################
POST http://afshin:4043/ddd/shopping/showproduct
Accept: application/json
Content-Type: application/json

{
  "code":null,
  "page":null
}
##### who #################################
POST http://afshin:4043/ddd/shopping/who
Accept: application/json
Content-Type: application/json

{
  "code":2
}