# http://mageddo.com/tools/yaml-converter
server:
  port: 8080
spring:
  application:
    name: Gateway
  cloud:
    loadbalancer:
      service-discovery:
        timeout: 3000
      configurations: default
      retry:
        max-retries-on-same-service-instance: 0
        max-retries-on-next-service-instance: 1
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: test-service-withResilient4j
          uri: http://localhost:8091
          predicates:
            - Path=/testService/**
          filters:
            - CircuitBreaker=backendA
# ----------- Eureka SD address for POST(Register),PUT(HeartBeat),Delete,Get
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.34:8761/eureka
# ---------------circuitbreaker resilience4j
resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-size: 10 #Wait for 10 calls
        minimum-number-of-calls: 5 #Count based wait min to 5 fail to open circuit
        permitted-number-of-calls-in-half-open-state: 3 #Toggle to close/open state
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s #Time based wait min to 5 fail to open circuit
        failure-rate-threshold: 50
        event-consumer-buffer-size: 10
      whoservice:
        record-exceptions:
          - com.afshin.gateway.application.fallback.PeopleResFB
       
    instances:
      whoami:
        base-config: default
      products:
        base-config: default