##### Show Product #################################
POST http://localhost:8080/ddd/product/showproduct
Accept: application/json
Content-Type: application/json

{
  "code":null,
  "page":null
}
##### who #################################
POST http://localhost:8080/ddd/people/who
Accept: application/json
Content-Type: application/json

{
  "code":2
}