###  http://192.168.1.34:8083/ddd/api-ui
##### Show Product #################################
POST http://localhost:8083/ddd/shopping/showproduct
Accept: application/json
Content-Type: application/json

{
  "code":null,
  "page":null
}
##### who #################################
POST http://localhost:8080/ddd/people/who
Accept: application/json
Content-Type: application/json

{
  "code":2
}