###  http://localhost:4042/ddd/api-ui
POST http://localhost:4042/ddd/product/find
Accept: application/json
Content-Type: application/json

{
  "code":null,
  "page":0
}
##################################################################################################
POST http://localhost:4042/ddd/product/quantity
Accept: application/json
Content-Type: application/json

[2,3,4,5]
##################################################################################################

DELETE http://localhost:4042/ddd/product/delete
Accept: application/json
Content-Type: application/json

{
    "code":38
}
##################################################################################################
PUT http://localhost:4042/ddd/product/save
Accept: application/json
Content-Type: application/json

{
  "productpk": null,
  "productname": "New 3D Samplea",
  "categoryfk": 3,
  "vendor": "Afshin Parhizkari Code Gen",
  "quantity": 1,
  "unit": "Kmeter",
  "buyprice": 10.00,
  "saleprice": 20.30,
  "active": true,
  "description": "This code generate for working with microservice tools."
}